### ISSUE TITLE
Update Killed Moodle Container

### ISSUE THREAD

**Issue by dylancaple** [bitnami/bitnami-docker-moodle#141]
**Description**

Hello. I Have recently attempted to update our Moodle Container on the unRAID WebGUI. After the update completed, the container now doesn't start and is inaccessible. Typically when we open https://training.swr999.com.au/ the site loads, now we get 502 bad gateway.
. 
![image](https://user-images.githubusercontent.com/68023668/93213148-d6499600-f7a6-11ea-8256-3d3c7633a205.png)

![image](https://user-images.githubusercontent.com/68023668/93213681-861f0380-f7a7-11ea-8d7d-064261e5f00b.png)

**Version**

- Output of `docker version`:

```
19.03.5
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 12
  Running: 10
  Paused: 0
  Stopped: 2
 Images: 11
 Server Version: 19.03.5
 Storage Driver: btrfs
  Build Version: Btrfs v4.7.3
  Library Version: 101
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.107-Unraid
 Operating System: Slackware 14.2 x86_64 (post 14.2 -current)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.97GiB
 Name: MainServer
 ID: FHAP:VIP6:2SKV:2K2B:E3I4:OM6W:HFUC:O3X2:LLLA:2JKW:JFAC:36YE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @dylancaple ,
Cold you share the container logs?

**Comment by dylancaple** [comment]
Hey @miguelaeh 

This is all I get on the log now.
![image](https://user-images.githubusercontent.com/68023668/93334987-1cffc480-f869-11ea-9bba-fb280dcc66e5.png)

**Comment by miguelaeh** [comment]
Hi @dylancaple ,
Can you connect to the container using ssh? How did you deploy it? 
Is it possible for you to execute:
```
docker logs <container-id>
```
?

**Comment by dylancaple** [comment]
Hey @miguelaeh,
I'm not sure how to connect using SSH. We deployed it just by installing it from https://hub.docker.com/r/bitnami/moodle/

When I executed docker logs, I got this: -bash: syntax error near unexpected token `newline'

**Comment by dylancaple** [comment]
Hmmm, not too sure on that one.
My manager installed Moodle a couple months back.
Will get back to you soon

**Comment by marcosbc** [comment]
Hi, could you try to update Moodle to 3.9.2-debian-10-r25? We fixed an issue reported in #142 that may fix this issue as well.

**Comment by dylancaple** [comment]
> an-

Hi,
I have tried this but unfortantley still no luck.
![image](https://user-images.githubusercontent.com/68023668/95547917-bdec3480-0a4f-11eb-8b88-16f67cdeebe6.png)

**Comment by marcosbc** [comment]
Hi @dylancaple, doesn't your Docker manager offer any way to retrieve stdout logs from your running containers? It would be really helpful to determine what is happening.

Also, if you were to retrieve those, please try running the container image with the environment variable `BITNAMI_DEBUG=true` to retrieve more info that could be useful for identifying what is happening.

**Comment by dylancaple** [comment]
> Hi @dylancaple, doesn't your Docker manager offer any way to retrieve stdout logs from your running containers? It would be really helpful to determine what is happening.
> 
> Also, if you were to retrieve those, please try running the container image with the environment variable `BITNAMI_DEBUG=true` to retrieve more info that could be useful for identifying what is happening.

Sorry for my tardy reply. Been busy with work. I'm not the most qualified in the server stuff, so how exactly would I run that on Unraid?

**Comment by miguelaeh** [comment]
Hi @dylancaple ,
I am sorry I have never used Unraid, but it seems those are the docs: https://wiki.unraid.net/UnRAID_6/Docker_Management
